# Generated by Django 5.2.6 on 2025-09-26 05:27

import django.core.validators
import students.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Reference ID')),
                ('full_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('enrolled_date', models.DateField()),
                ('course_name', models.CharField(choices=[('web_development', 'Web Development'), ('data_science', 'Data Science'), ('digital_marketing', 'Digital Marketing'), ('graphic_design', 'Graphic Design'), ('mobile_app_development', 'Mobile App Development'), ('python_programming', 'Python Programming'), ('java_programming', 'Java Programming'), ('cyber_security', 'Cyber Security')], max_length=50)),
                ('course_duration', models.CharField(help_text='e.g., 3 months, 6 months, etc.', max_length=50)),
                ('mode_of_learning', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online')], max_length=10)),
                ('instructor_name', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(help_text='Upload a JPG or PNG image', upload_to=students.models.student_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('email_address', models.EmailField(max_length=254)),
                ('batch_schedule', models.CharField(blank=True, help_text='Only required for physical mode (e.g., Mon-Wed-Fri 10:00 AM)', max_length=100, null=True)),
                ('approve_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
