# Generated by Django 5.2.6 on 2025-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('enrolled_date', models.DateField()),
                ('course_name', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=255)),
                ('mode_of_learning', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], max_length=10)),
                ('batch_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor_name', models.CharField(max_length=255)),
                ('student_photo', models.ImageField(upload_to='student_photos/')),
                ('email_address', models.EmailField(max_length=254)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
    ]
