# Generated by Django 5.2.6 on 2025-09-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Unique code for certificate verification', max_length=32, unique=True),
        ),
    ]
